services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - app_net

  nginx:
         : nginx:1.27-alpine
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
