services:
  api:
    image: hasnahasan/carevoyage-api:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - app_net

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
